### PR TITLE
Send Bytes over the network instead of Strings

### PR DESCRIPTION
**Pull request by ugnmura**
This PR allows the application to send bytes over the network rather than using strings. Note that the message still remain strings, they are just converted to byte arrays before sending.

### CODE REVIEW

**Comment by Duckulus** [comment]
I think sending bytes over the network is a very logical approach. I just think that the way it was implemented is not really flexible. A [ByteBuffer](https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html) would allow us to structure Packet data in a better way and also send other primitive data types.

**Comment by ugnmura** [comment]
I think we need to abstract the messaging system away, do you think having a message class for every message type is a good idea?

**Comment by Duckulus** [comment]
Yeah, that would certainly work. We can make advantage of Javas oop capabilities and define a message as an abstract superclass that all other Message types inherit from. Then we can send all kinds of messages by serializing them or wrapping them in ByteBuffers

**Comment by ugnmura** [comment]
Currently the serialization is kinda hard to do, it would be nice to add that feature in the future. For now I think this is pretty manageable.

**Comment by Duckulus** [comment]
Alright, thank you very much for your contribution!

**Pull request merged**
